// flow-typed signature: 1337b7210d228fc438075ecd083ad4d2
// flow-typed version: <<STUB>>/bcrypt-as-promised_v^1.1.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bcrypt-as-promised'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bcrypt-as-promised' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bcrypt-as-promised/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bcrypt-as-promised/index' {
  declare module.exports: $Exports<'bcrypt-as-promised'>;
}
declare module 'bcrypt-as-promised/index.js' {
  declare module.exports: $Exports<'bcrypt-as-promised'>;
}
declare module 'bcrypt-as-promised/test/index.js' {
  declare module.exports: $Exports<'bcrypt-as-promised/test/index'>;
}
