// flow-typed signature: 73472b296fb6b664764cf68ecb14ed35
// flow-typed version: <<STUB>>/dotenv-safe_v^4.0.4/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dotenv-safe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dotenv-safe' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dotenv-safe/config' {
  declare module.exports: any;
}

declare module 'dotenv-safe/MissingEnvVarsError' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dotenv-safe/config.js' {
  declare module.exports: $Exports<'dotenv-safe/config'>;
}
declare module 'dotenv-safe/index' {
  declare module.exports: $Exports<'dotenv-safe'>;
}
declare module 'dotenv-safe/index.js' {
  declare module.exports: $Exports<'dotenv-safe'>;
}
declare module 'dotenv-safe/MissingEnvVarsError.js' {
  declare module.exports: $Exports<'dotenv-safe/MissingEnvVarsError'>;
}
