// flow-typed signature: ecfb1138a666eba69173c6cfe3f1bac2
// flow-typed version: <<STUB>>/koa-compose_v^4.0.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-compose'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-compose' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'koa-compose/index' {
  declare module.exports: $Exports<'koa-compose'>;
}
declare module 'koa-compose/index.js' {
  declare module.exports: $Exports<'koa-compose'>;
}
