// flow-typed signature: 02d812c520427cb211b82d27b5865a9e
// flow-typed version: <<STUB>>/koa-cors_v0.0.16/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-cors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-cors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-cors/examples/basic-auth-and-cors' {
  declare module.exports: any;
}

declare module 'koa-cors/examples/custom-options' {
  declare module.exports: any;
}

declare module 'koa-cors/examples/defaults-options' {
  declare module.exports: any;
}

declare module 'koa-cors/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-cors/examples/basic-auth-and-cors.js' {
  declare module.exports: $Exports<'koa-cors/examples/basic-auth-and-cors'>;
}
declare module 'koa-cors/examples/custom-options.js' {
  declare module.exports: $Exports<'koa-cors/examples/custom-options'>;
}
declare module 'koa-cors/examples/defaults-options.js' {
  declare module.exports: $Exports<'koa-cors/examples/defaults-options'>;
}
declare module 'koa-cors/index' {
  declare module.exports: $Exports<'koa-cors'>;
}
declare module 'koa-cors/index.js' {
  declare module.exports: $Exports<'koa-cors'>;
}
declare module 'koa-cors/test/index.js' {
  declare module.exports: $Exports<'koa-cors/test/index'>;
}
