// flow-typed signature: 2716bccab7716f0d52a5be0ffe60bf84
// flow-typed version: <<STUB>>/koa-graphql_v^0.6.2/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-graphql'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-graphql' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-graphql/dist/index' {
  declare module.exports: any;
}

declare module 'koa-graphql/dist/renderGraphiQL' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-graphql/dist/index.js' {
  declare module.exports: $Exports<'koa-graphql/dist/index'>;
}
declare module 'koa-graphql/dist/renderGraphiQL.js' {
  declare module.exports: $Exports<'koa-graphql/dist/renderGraphiQL'>;
}
