// flow-typed signature: bdd24183f1fd5f0b908ec716a2d280c7
// flow-typed version: <<STUB>>/reify_v^0.11.23/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reify/lib/assignment-visitor' {
  declare module.exports: any;
}

declare module 'reify/lib/compiler' {
  declare module.exports: any;
}

declare module 'reify/lib/empty' {
  declare module.exports: any;
}

declare module 'reify/lib/fast-object' {
  declare module.exports: any;
}

declare module 'reify/lib/fast-path' {
  declare module.exports: any;
}

declare module 'reify/lib/import-export-visitor' {
  declare module.exports: any;
}

declare module 'reify/lib/magic-string' {
  declare module.exports: any;
}

declare module 'reify/lib/options' {
  declare module.exports: any;
}

declare module 'reify/lib/parsers/acorn-extensions/export' {
  declare module.exports: any;
}

declare module 'reify/lib/parsers/acorn-extensions/import' {
  declare module.exports: any;
}

declare module 'reify/lib/parsers/acorn-extensions/index' {
  declare module.exports: any;
}

declare module 'reify/lib/parsers/acorn-extensions/tolerance' {
  declare module.exports: any;
}

declare module 'reify/lib/parsers/acorn' {
  declare module.exports: any;
}

declare module 'reify/lib/parsers/babylon' {
  declare module.exports: any;
}

declare module 'reify/lib/parsers/default' {
  declare module.exports: any;
}

declare module 'reify/lib/parsers/top-level' {
  declare module.exports: any;
}

declare module 'reify/lib/runtime/entry' {
  declare module.exports: any;
}

declare module 'reify/lib/runtime/index' {
  declare module.exports: any;
}

declare module 'reify/lib/runtime/utils' {
  declare module.exports: any;
}

declare module 'reify/lib/transform' {
  declare module.exports: any;
}

declare module 'reify/lib/utils' {
  declare module.exports: any;
}

declare module 'reify/lib/visitor' {
  declare module.exports: any;
}

declare module 'reify/node/caching-compiler' {
  declare module.exports: any;
}

declare module 'reify/node/compile-hook' {
  declare module.exports: any;
}

declare module 'reify/node/data' {
  declare module.exports: any;
}

declare module 'reify/node/fs' {
  declare module.exports: any;
}

declare module 'reify/node/index' {
  declare module.exports: any;
}

declare module 'reify/node/pkg-info' {
  declare module.exports: any;
}

declare module 'reify/node/repl-hook' {
  declare module.exports: any;
}

declare module 'reify/node/utils' {
  declare module.exports: any;
}

declare module 'reify/node/version' {
  declare module.exports: any;
}

declare module 'reify/node/wrapper' {
  declare module.exports: any;
}

declare module 'reify/repl/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reify/lib/assignment-visitor.js' {
  declare module.exports: $Exports<'reify/lib/assignment-visitor'>;
}
declare module 'reify/lib/compiler.js' {
  declare module.exports: $Exports<'reify/lib/compiler'>;
}
declare module 'reify/lib/empty.js' {
  declare module.exports: $Exports<'reify/lib/empty'>;
}
declare module 'reify/lib/fast-object.js' {
  declare module.exports: $Exports<'reify/lib/fast-object'>;
}
declare module 'reify/lib/fast-path.js' {
  declare module.exports: $Exports<'reify/lib/fast-path'>;
}
declare module 'reify/lib/import-export-visitor.js' {
  declare module.exports: $Exports<'reify/lib/import-export-visitor'>;
}
declare module 'reify/lib/magic-string.js' {
  declare module.exports: $Exports<'reify/lib/magic-string'>;
}
declare module 'reify/lib/options.js' {
  declare module.exports: $Exports<'reify/lib/options'>;
}
declare module 'reify/lib/parsers/acorn-extensions/export.js' {
  declare module.exports: $Exports<'reify/lib/parsers/acorn-extensions/export'>;
}
declare module 'reify/lib/parsers/acorn-extensions/import.js' {
  declare module.exports: $Exports<'reify/lib/parsers/acorn-extensions/import'>;
}
declare module 'reify/lib/parsers/acorn-extensions/index.js' {
  declare module.exports: $Exports<'reify/lib/parsers/acorn-extensions/index'>;
}
declare module 'reify/lib/parsers/acorn-extensions/tolerance.js' {
  declare module.exports: $Exports<'reify/lib/parsers/acorn-extensions/tolerance'>;
}
declare module 'reify/lib/parsers/acorn.js' {
  declare module.exports: $Exports<'reify/lib/parsers/acorn'>;
}
declare module 'reify/lib/parsers/babylon.js' {
  declare module.exports: $Exports<'reify/lib/parsers/babylon'>;
}
declare module 'reify/lib/parsers/default.js' {
  declare module.exports: $Exports<'reify/lib/parsers/default'>;
}
declare module 'reify/lib/parsers/top-level.js' {
  declare module.exports: $Exports<'reify/lib/parsers/top-level'>;
}
declare module 'reify/lib/runtime/entry.js' {
  declare module.exports: $Exports<'reify/lib/runtime/entry'>;
}
declare module 'reify/lib/runtime/index.js' {
  declare module.exports: $Exports<'reify/lib/runtime/index'>;
}
declare module 'reify/lib/runtime/utils.js' {
  declare module.exports: $Exports<'reify/lib/runtime/utils'>;
}
declare module 'reify/lib/transform.js' {
  declare module.exports: $Exports<'reify/lib/transform'>;
}
declare module 'reify/lib/utils.js' {
  declare module.exports: $Exports<'reify/lib/utils'>;
}
declare module 'reify/lib/visitor.js' {
  declare module.exports: $Exports<'reify/lib/visitor'>;
}
declare module 'reify/node/caching-compiler.js' {
  declare module.exports: $Exports<'reify/node/caching-compiler'>;
}
declare module 'reify/node/compile-hook.js' {
  declare module.exports: $Exports<'reify/node/compile-hook'>;
}
declare module 'reify/node/data.js' {
  declare module.exports: $Exports<'reify/node/data'>;
}
declare module 'reify/node/fs.js' {
  declare module.exports: $Exports<'reify/node/fs'>;
}
declare module 'reify/node/index.js' {
  declare module.exports: $Exports<'reify/node/index'>;
}
declare module 'reify/node/pkg-info.js' {
  declare module.exports: $Exports<'reify/node/pkg-info'>;
}
declare module 'reify/node/repl-hook.js' {
  declare module.exports: $Exports<'reify/node/repl-hook'>;
}
declare module 'reify/node/utils.js' {
  declare module.exports: $Exports<'reify/node/utils'>;
}
declare module 'reify/node/version.js' {
  declare module.exports: $Exports<'reify/node/version'>;
}
declare module 'reify/node/wrapper.js' {
  declare module.exports: $Exports<'reify/node/wrapper'>;
}
declare module 'reify/repl/index.js' {
  declare module.exports: $Exports<'reify/repl/index'>;
}
