// flow-typed signature: 2e8e406a416c4adee333aeab14221385
// flow-typed version: <<STUB>>/repl.history_v^0.1.4/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'repl.history'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'repl.history' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'repl.history/index' {
  declare module.exports: $Exports<'repl.history'>;
}
declare module 'repl.history/index.js' {
  declare module.exports: $Exports<'repl.history'>;
}
